// flow-typed signature: 9c91ff113cc1a3862b01c6b7d325408c
// flow-typed version: <<STUB>>/braintree-web_v2.24.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'braintree-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'braintree-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'braintree-web/dist/braintree' {
  declare module.exports: any;
}

// Filename aliases
declare module 'braintree-web/dist/braintree.js' {
  declare module.exports: $Exports<'braintree-web/dist/braintree'>;
}
