// flow-typed signature: 4d753a7af6274b55bb0b9dcee1ddd109
// flow-typed version: <<STUB>>/catl-step_v1.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'catl-step'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'catl-step' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'catl-step/lib/decorators' {
  declare module.exports: any;
}

declare module 'catl-step/lib/index' {
  declare module.exports: any;
}

declare module 'catl-step/lib/middlewares' {
  declare module.exports: any;
}

declare module 'catl-step/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'catl-step/lib/decorators.js' {
  declare module.exports: $Exports<'catl-step/lib/decorators'>;
}
declare module 'catl-step/lib/index.js' {
  declare module.exports: $Exports<'catl-step/lib/index'>;
}
declare module 'catl-step/lib/middlewares.js' {
  declare module.exports: $Exports<'catl-step/lib/middlewares'>;
}
declare module 'catl-step/lib/utils.js' {
  declare module.exports: $Exports<'catl-step/lib/utils'>;
}
