// flow-typed signature: 872b14d020566d814e42b7d3d366fa49
// flow-typed version: <<STUB>>/catl-deploy-ssh_v1.0.35/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'catl-deploy-ssh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'catl-deploy-ssh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'catl-deploy-ssh/lib/index' {
  declare module.exports: any;
}

declare module 'catl-deploy-ssh/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'catl-deploy-ssh/lib/index.js' {
  declare module.exports: $Exports<'catl-deploy-ssh/lib/index'>;
}
declare module 'catl-deploy-ssh/lib/utils.js' {
  declare module.exports: $Exports<'catl-deploy-ssh/lib/utils'>;
}
