// flow-typed signature: b4f768b18c43f3a16cbf1d859cd5f26d
// flow-typed version: <<STUB>>/catl-cli_v^4.6.16-aws-eb.27/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'catl-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'catl-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'catl-cli/bin/catl' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/@bahmutov/parse-github-repo-url_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/babel-polyfill_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/babel-preset-catl_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/babel-register_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/base32_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/chalk_v1.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/child-process-promise_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/conventional-changelog_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/es6-promisify_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/github_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/github-url-from-git_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/ini_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/inquirer-promise_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/isomorphic-fetch_v2.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/jest_v19.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/js-yaml_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/mkdirp_v0.5.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/moment_v2.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/nerf-dart_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/npm-registry-client_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/npmlog_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/opn_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/parse-github-repo-url_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/path-to-regexp_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/pull-request_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/ramda_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/remote-redux-devtools_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/replay_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/request_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/rimraf_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/ssh-exec_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/stream-to-promise_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/travis-ci_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/travis-status_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/validator_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/vorpal_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow-typed/npm/ws_vx.x.x' {
  declare module.exports: any;
}

declare module 'catl-cli/flow/interfaces/main' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/error' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-generic-steps/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-generic-steps/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/consts' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/createStep' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/decorators/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/decorators/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/hooks/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/hooks/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/middlewares' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/testModule' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/tree/bigTree' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/tree/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/tree/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/types' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/catl-step/utils' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/router/matchPath' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/ext/router/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/routes/aws_eb' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/routes/github' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/routes/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/routes/utils' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/methods/analyzeReleases' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/methods/generateCIScriptConfig/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/methods/generateNotes/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/methods/generateNotes/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/methods/getCommits/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/methods/getCommits/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/methods/getNextRelease/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/methods/getTypeOfChange/analyzeCommits' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/methods/getTypeOfChange/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/methods/getTypeOfChange/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/methods/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/profiles/classic' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/profiles/dockerCircleCI' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/profiles/dockerCodeship' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/profiles/dockerTravis' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/scripts/init/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/scripts/init/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/scripts/onCI/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/scripts/onCI/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/semanticRelease/share' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/aws_eb/api' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/aws_eb/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/aws_eb/lowApi' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/aws/auth' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/aws/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/circleci/auth' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/circleci/generateFiles' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/circleci/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/circleci/provide' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/circleci/types' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/codeship/auth' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/codeship/generateFiles' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/codeship/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/codeship/provide' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/share' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/travis/auth/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/travis/cliSetCIEnvironment' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/travis/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/travis/provide' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/travis/syncTravis' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ci/travis/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/exec' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/fs' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/log' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/open' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/promisify' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/request' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/secret/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/secret/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/spawn/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/sshApi/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/sshApi/ssh-exec' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/steps/storage' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/core/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/deployShared' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/docker/api' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/docker/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/docker/verify' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/dockerSwarm/api' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/dockerSwarm/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/git/getLastRelease/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/git/getLastRelease/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/git/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/github/createAuthorization' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/github/createRelease/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/github/createRelease/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/github/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/github/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/npm/auth/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/npm/getLastRelease/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/npm/getLatestCatlVersion/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/npm/getLatestCatlVersion/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/npm/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/npm/saveConf/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/npm/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/npm/writePackageJson/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/npm/writePackageJson/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/repository/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/repository/test' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/ssh/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/types' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/subjects/utils' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/utils/index' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/vorpal.babel' {
  declare module.exports: any;
}

declare module 'catl-cli/lib/vorpal' {
  declare module.exports: any;
}

declare module 'catl-cli/test/mocks/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'catl-cli/bin/catl.js' {
  declare module.exports: $Exports<'catl-cli/bin/catl'>;
}
declare module 'catl-cli/flow-typed/npm/@bahmutov/parse-github-repo-url_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/@bahmutov/parse-github-repo-url_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/babel-polyfill_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/babel-polyfill_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/babel-preset-catl_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/babel-preset-catl_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/babel-register_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/babel-register_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/base32_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/base32_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/chalk_v1.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/chalk_v1.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/child-process-promise_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/child-process-promise_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/conventional-changelog_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/conventional-changelog_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/es6-promisify_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/es6-promisify_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/github_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/github_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/github-url-from-git_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/github-url-from-git_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/ini_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/ini_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/inquirer-promise_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/inquirer-promise_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/isomorphic-fetch_v2.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/isomorphic-fetch_v2.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/jest_v19.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/jest_v19.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/js-yaml_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/js-yaml_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/mkdirp_v0.5.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/mkdirp_v0.5.x'>;
}
declare module 'catl-cli/flow-typed/npm/moment_v2.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/moment_v2.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/nerf-dart_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/nerf-dart_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/npm-registry-client_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/npm-registry-client_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/npmlog_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/npmlog_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/opn_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/opn_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/parse-github-repo-url_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/parse-github-repo-url_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/path-to-regexp_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/path-to-regexp_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/pull-request_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/pull-request_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/ramda_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/ramda_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/remote-redux-devtools_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/remote-redux-devtools_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/replay_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/replay_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/request_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/request_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/rimraf_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/rimraf_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/ssh-exec_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/ssh-exec_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/stream-to-promise_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/stream-to-promise_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/travis-ci_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/travis-ci_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/travis-status_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/travis-status_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/validator_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/validator_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/vorpal_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/vorpal_vx.x.x'>;
}
declare module 'catl-cli/flow-typed/npm/ws_vx.x.x.js' {
  declare module.exports: $Exports<'catl-cli/flow-typed/npm/ws_vx.x.x'>;
}
declare module 'catl-cli/flow/interfaces/main.js' {
  declare module.exports: $Exports<'catl-cli/flow/interfaces/main'>;
}
declare module 'catl-cli/lib/error.js' {
  declare module.exports: $Exports<'catl-cli/lib/error'>;
}
declare module 'catl-cli/lib/ext/catl-generic-steps/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-generic-steps/index'>;
}
declare module 'catl-cli/lib/ext/catl-generic-steps/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-generic-steps/test'>;
}
declare module 'catl-cli/lib/ext/catl-step/consts.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/consts'>;
}
declare module 'catl-cli/lib/ext/catl-step/createStep.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/createStep'>;
}
declare module 'catl-cli/lib/ext/catl-step/decorators/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/decorators/index'>;
}
declare module 'catl-cli/lib/ext/catl-step/decorators/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/decorators/test'>;
}
declare module 'catl-cli/lib/ext/catl-step/hooks/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/hooks/index'>;
}
declare module 'catl-cli/lib/ext/catl-step/hooks/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/hooks/test'>;
}
declare module 'catl-cli/lib/ext/catl-step/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/index'>;
}
declare module 'catl-cli/lib/ext/catl-step/middlewares.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/middlewares'>;
}
declare module 'catl-cli/lib/ext/catl-step/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/test'>;
}
declare module 'catl-cli/lib/ext/catl-step/testModule.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/testModule'>;
}
declare module 'catl-cli/lib/ext/catl-step/tree/bigTree.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/tree/bigTree'>;
}
declare module 'catl-cli/lib/ext/catl-step/tree/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/tree/index'>;
}
declare module 'catl-cli/lib/ext/catl-step/tree/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/tree/test'>;
}
declare module 'catl-cli/lib/ext/catl-step/types.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/types'>;
}
declare module 'catl-cli/lib/ext/catl-step/utils.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/catl-step/utils'>;
}
declare module 'catl-cli/lib/ext/router/matchPath.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/router/matchPath'>;
}
declare module 'catl-cli/lib/ext/router/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/ext/router/test'>;
}
declare module 'catl-cli/lib/routes/aws_eb.js' {
  declare module.exports: $Exports<'catl-cli/lib/routes/aws_eb'>;
}
declare module 'catl-cli/lib/routes/github.js' {
  declare module.exports: $Exports<'catl-cli/lib/routes/github'>;
}
declare module 'catl-cli/lib/routes/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/routes/index'>;
}
declare module 'catl-cli/lib/routes/utils.js' {
  declare module.exports: $Exports<'catl-cli/lib/routes/utils'>;
}
declare module 'catl-cli/lib/semanticRelease/methods/analyzeReleases.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/methods/analyzeReleases'>;
}
declare module 'catl-cli/lib/semanticRelease/methods/generateCIScriptConfig/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/methods/generateCIScriptConfig/index'>;
}
declare module 'catl-cli/lib/semanticRelease/methods/generateNotes/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/methods/generateNotes/index'>;
}
declare module 'catl-cli/lib/semanticRelease/methods/generateNotes/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/methods/generateNotes/test'>;
}
declare module 'catl-cli/lib/semanticRelease/methods/getCommits/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/methods/getCommits/index'>;
}
declare module 'catl-cli/lib/semanticRelease/methods/getCommits/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/methods/getCommits/test'>;
}
declare module 'catl-cli/lib/semanticRelease/methods/getNextRelease/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/methods/getNextRelease/index'>;
}
declare module 'catl-cli/lib/semanticRelease/methods/getTypeOfChange/analyzeCommits.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/methods/getTypeOfChange/analyzeCommits'>;
}
declare module 'catl-cli/lib/semanticRelease/methods/getTypeOfChange/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/methods/getTypeOfChange/index'>;
}
declare module 'catl-cli/lib/semanticRelease/methods/getTypeOfChange/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/methods/getTypeOfChange/test'>;
}
declare module 'catl-cli/lib/semanticRelease/methods/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/methods/index'>;
}
declare module 'catl-cli/lib/semanticRelease/profiles/classic.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/profiles/classic'>;
}
declare module 'catl-cli/lib/semanticRelease/profiles/dockerCircleCI.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/profiles/dockerCircleCI'>;
}
declare module 'catl-cli/lib/semanticRelease/profiles/dockerCodeship.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/profiles/dockerCodeship'>;
}
declare module 'catl-cli/lib/semanticRelease/profiles/dockerTravis.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/profiles/dockerTravis'>;
}
declare module 'catl-cli/lib/semanticRelease/scripts/init/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/scripts/init/index'>;
}
declare module 'catl-cli/lib/semanticRelease/scripts/init/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/scripts/init/test'>;
}
declare module 'catl-cli/lib/semanticRelease/scripts/onCI/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/scripts/onCI/index'>;
}
declare module 'catl-cli/lib/semanticRelease/scripts/onCI/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/scripts/onCI/test'>;
}
declare module 'catl-cli/lib/semanticRelease/share.js' {
  declare module.exports: $Exports<'catl-cli/lib/semanticRelease/share'>;
}
declare module 'catl-cli/lib/subjects/aws_eb/api.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/aws_eb/api'>;
}
declare module 'catl-cli/lib/subjects/aws_eb/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/aws_eb/index'>;
}
declare module 'catl-cli/lib/subjects/aws_eb/lowApi.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/aws_eb/lowApi'>;
}
declare module 'catl-cli/lib/subjects/aws/auth.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/aws/auth'>;
}
declare module 'catl-cli/lib/subjects/aws/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/aws/index'>;
}
declare module 'catl-cli/lib/subjects/ci/circleci/auth.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/circleci/auth'>;
}
declare module 'catl-cli/lib/subjects/ci/circleci/generateFiles.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/circleci/generateFiles'>;
}
declare module 'catl-cli/lib/subjects/ci/circleci/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/circleci/index'>;
}
declare module 'catl-cli/lib/subjects/ci/circleci/provide.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/circleci/provide'>;
}
declare module 'catl-cli/lib/subjects/ci/circleci/types.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/circleci/types'>;
}
declare module 'catl-cli/lib/subjects/ci/codeship/auth.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/codeship/auth'>;
}
declare module 'catl-cli/lib/subjects/ci/codeship/generateFiles.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/codeship/generateFiles'>;
}
declare module 'catl-cli/lib/subjects/ci/codeship/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/codeship/index'>;
}
declare module 'catl-cli/lib/subjects/ci/codeship/provide.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/codeship/provide'>;
}
declare module 'catl-cli/lib/subjects/ci/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/index'>;
}
declare module 'catl-cli/lib/subjects/ci/share.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/share'>;
}
declare module 'catl-cli/lib/subjects/ci/travis/auth/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/travis/auth/index'>;
}
declare module 'catl-cli/lib/subjects/ci/travis/cliSetCIEnvironment.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/travis/cliSetCIEnvironment'>;
}
declare module 'catl-cli/lib/subjects/ci/travis/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/travis/index'>;
}
declare module 'catl-cli/lib/subjects/ci/travis/provide.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/travis/provide'>;
}
declare module 'catl-cli/lib/subjects/ci/travis/syncTravis.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/travis/syncTravis'>;
}
declare module 'catl-cli/lib/subjects/ci/travis/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ci/travis/test'>;
}
declare module 'catl-cli/lib/subjects/core/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/index'>;
}
declare module 'catl-cli/lib/subjects/core/steps/exec.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/exec'>;
}
declare module 'catl-cli/lib/subjects/core/steps/fs.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/fs'>;
}
declare module 'catl-cli/lib/subjects/core/steps/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/index'>;
}
declare module 'catl-cli/lib/subjects/core/steps/log.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/log'>;
}
declare module 'catl-cli/lib/subjects/core/steps/open.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/open'>;
}
declare module 'catl-cli/lib/subjects/core/steps/promisify.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/promisify'>;
}
declare module 'catl-cli/lib/subjects/core/steps/request.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/request'>;
}
declare module 'catl-cli/lib/subjects/core/steps/secret/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/secret/index'>;
}
declare module 'catl-cli/lib/subjects/core/steps/secret/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/secret/test'>;
}
declare module 'catl-cli/lib/subjects/core/steps/spawn/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/spawn/index'>;
}
declare module 'catl-cli/lib/subjects/core/steps/sshApi/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/sshApi/index'>;
}
declare module 'catl-cli/lib/subjects/core/steps/sshApi/ssh-exec.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/sshApi/ssh-exec'>;
}
declare module 'catl-cli/lib/subjects/core/steps/storage.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/steps/storage'>;
}
declare module 'catl-cli/lib/subjects/core/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/core/test'>;
}
declare module 'catl-cli/lib/subjects/deployShared.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/deployShared'>;
}
declare module 'catl-cli/lib/subjects/docker/api.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/docker/api'>;
}
declare module 'catl-cli/lib/subjects/docker/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/docker/index'>;
}
declare module 'catl-cli/lib/subjects/docker/verify.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/docker/verify'>;
}
declare module 'catl-cli/lib/subjects/dockerSwarm/api.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/dockerSwarm/api'>;
}
declare module 'catl-cli/lib/subjects/dockerSwarm/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/dockerSwarm/index'>;
}
declare module 'catl-cli/lib/subjects/git/getLastRelease/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/git/getLastRelease/index'>;
}
declare module 'catl-cli/lib/subjects/git/getLastRelease/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/git/getLastRelease/test'>;
}
declare module 'catl-cli/lib/subjects/git/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/git/index'>;
}
declare module 'catl-cli/lib/subjects/github/createAuthorization.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/github/createAuthorization'>;
}
declare module 'catl-cli/lib/subjects/github/createRelease/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/github/createRelease/index'>;
}
declare module 'catl-cli/lib/subjects/github/createRelease/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/github/createRelease/test'>;
}
declare module 'catl-cli/lib/subjects/github/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/github/index'>;
}
declare module 'catl-cli/lib/subjects/github/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/github/test'>;
}
declare module 'catl-cli/lib/subjects/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/index'>;
}
declare module 'catl-cli/lib/subjects/npm/auth/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/npm/auth/index'>;
}
declare module 'catl-cli/lib/subjects/npm/getLastRelease/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/npm/getLastRelease/index'>;
}
declare module 'catl-cli/lib/subjects/npm/getLatestCatlVersion/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/npm/getLatestCatlVersion/index'>;
}
declare module 'catl-cli/lib/subjects/npm/getLatestCatlVersion/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/npm/getLatestCatlVersion/test'>;
}
declare module 'catl-cli/lib/subjects/npm/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/npm/index'>;
}
declare module 'catl-cli/lib/subjects/npm/saveConf/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/npm/saveConf/index'>;
}
declare module 'catl-cli/lib/subjects/npm/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/npm/test'>;
}
declare module 'catl-cli/lib/subjects/npm/writePackageJson/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/npm/writePackageJson/index'>;
}
declare module 'catl-cli/lib/subjects/npm/writePackageJson/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/npm/writePackageJson/test'>;
}
declare module 'catl-cli/lib/subjects/repository/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/repository/index'>;
}
declare module 'catl-cli/lib/subjects/repository/test.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/repository/test'>;
}
declare module 'catl-cli/lib/subjects/ssh/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/ssh/index'>;
}
declare module 'catl-cli/lib/subjects/types.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/types'>;
}
declare module 'catl-cli/lib/subjects/utils.js' {
  declare module.exports: $Exports<'catl-cli/lib/subjects/utils'>;
}
declare module 'catl-cli/lib/utils/index.js' {
  declare module.exports: $Exports<'catl-cli/lib/utils/index'>;
}
declare module 'catl-cli/lib/vorpal.babel.js' {
  declare module.exports: $Exports<'catl-cli/lib/vorpal.babel'>;
}
declare module 'catl-cli/lib/vorpal.js' {
  declare module.exports: $Exports<'catl-cli/lib/vorpal'>;
}
declare module 'catl-cli/test/mocks/index.js' {
  declare module.exports: $Exports<'catl-cli/test/mocks/index'>;
}
