// flow-typed signature: 81a3d23ad7f53b303a9cebd27d0a8b88
// flow-typed version: <<STUB>>/concurrently_v2.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'concurrently'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'concurrently' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'concurrently/src/main' {
  declare module.exports: any;
}

declare module 'concurrently/test' {
  declare module.exports: any;
}

declare module 'concurrently/test/test-functional' {
  declare module.exports: any;
}

declare module 'concurrently/test/utils' {
  declare module.exports: any;
}

declare module 'concurrently/tools/release' {
  declare module.exports: any;
}

// Filename aliases
declare module 'concurrently/src/main.js' {
  declare module.exports: $Exports<'concurrently/src/main'>;
}
declare module 'concurrently/test.js' {
  declare module.exports: $Exports<'concurrently/test'>;
}
declare module 'concurrently/test/test-functional.js' {
  declare module.exports: $Exports<'concurrently/test/test-functional'>;
}
declare module 'concurrently/test/utils.js' {
  declare module.exports: $Exports<'concurrently/test/utils'>;
}
declare module 'concurrently/tools/release.js' {
  declare module.exports: $Exports<'concurrently/tools/release'>;
}
