// flow-typed signature: 38a3c12139282443474786543c6a6c16
// flow-typed version: <<STUB>>/cron_v1.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cron/lib/cron-parser' {
  declare module.exports: any;
}

declare module 'cron/lib/cron' {
  declare module.exports: any;
}

declare module 'cron/test' {
  declare module.exports: any;
}

declare module 'cron/tests/test-cron' {
  declare module.exports: any;
}

declare module 'cron/tests/test-crontime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cron/lib/cron-parser.js' {
  declare module.exports: $Exports<'cron/lib/cron-parser'>;
}
declare module 'cron/lib/cron.js' {
  declare module.exports: $Exports<'cron/lib/cron'>;
}
declare module 'cron/test.js' {
  declare module.exports: $Exports<'cron/test'>;
}
declare module 'cron/tests/test-cron.js' {
  declare module.exports: $Exports<'cron/tests/test-cron'>;
}
declare module 'cron/tests/test-crontime.js' {
  declare module.exports: $Exports<'cron/tests/test-crontime'>;
}
