// flow-typed signature: 35537cb393b34fae38d79c60613a3b52
// flow-typed version: <<STUB>>/git-branch_v^0.3.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-branch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-branch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'git-branch/index' {
  declare module.exports: $Exports<'git-branch'>;
}
declare module 'git-branch/index.js' {
  declare module.exports: $Exports<'git-branch'>;
}
