// flow-typed signature: 304874faf0e3c8057b33f5e91bc45be4
// flow-typed version: <<STUB>>/google-map-react_v0.12.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'google-map-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'google-map-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'google-map-react/dist/GoogleMapReact' {
  declare module.exports: any;
}

declare module 'google-map-react/dist/GoogleMapReact.min' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/google_map_map' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/google_map_markers_prerender' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/google_map_markers' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/google_map' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/index' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/marker_dispatcher' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/array_helper' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/detect' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/geo' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/index' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/is_plain_object' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/lib_geo/lat_lng_bounds' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/lib_geo/lat_lng' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/lib_geo/transform' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/lib_geo/wrap' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/loaders/google_map_loader' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/math/log2' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/pick' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/raf' {
  declare module.exports: any;
}

declare module 'google-map-react/lib/utils/utils' {
  declare module.exports: any;
}

declare module 'google-map-react/test/components/GoogleMap.spec' {
  declare module.exports: any;
}

declare module 'google-map-react/test/components/utils/jsdomInit' {
  declare module.exports: any;
}

declare module 'google-map-react/utils/index' {
  declare module.exports: any;
}

declare module 'google-map-react/webpack.config.base' {
  declare module.exports: any;
}

declare module 'google-map-react/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'google-map-react/webpack.config.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'google-map-react/dist/GoogleMapReact.js' {
  declare module.exports: $Exports<'google-map-react/dist/GoogleMapReact'>;
}
declare module 'google-map-react/dist/GoogleMapReact.min.js' {
  declare module.exports: $Exports<'google-map-react/dist/GoogleMapReact.min'>;
}
declare module 'google-map-react/lib/google_map_map.js' {
  declare module.exports: $Exports<'google-map-react/lib/google_map_map'>;
}
declare module 'google-map-react/lib/google_map_markers_prerender.js' {
  declare module.exports: $Exports<'google-map-react/lib/google_map_markers_prerender'>;
}
declare module 'google-map-react/lib/google_map_markers.js' {
  declare module.exports: $Exports<'google-map-react/lib/google_map_markers'>;
}
declare module 'google-map-react/lib/google_map.js' {
  declare module.exports: $Exports<'google-map-react/lib/google_map'>;
}
declare module 'google-map-react/lib/index.js' {
  declare module.exports: $Exports<'google-map-react/lib/index'>;
}
declare module 'google-map-react/lib/marker_dispatcher.js' {
  declare module.exports: $Exports<'google-map-react/lib/marker_dispatcher'>;
}
declare module 'google-map-react/lib/utils/array_helper.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/array_helper'>;
}
declare module 'google-map-react/lib/utils/detect.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/detect'>;
}
declare module 'google-map-react/lib/utils/geo.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/geo'>;
}
declare module 'google-map-react/lib/utils/index.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/index'>;
}
declare module 'google-map-react/lib/utils/is_plain_object.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/is_plain_object'>;
}
declare module 'google-map-react/lib/utils/lib_geo/lat_lng_bounds.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/lib_geo/lat_lng_bounds'>;
}
declare module 'google-map-react/lib/utils/lib_geo/lat_lng.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/lib_geo/lat_lng'>;
}
declare module 'google-map-react/lib/utils/lib_geo/transform.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/lib_geo/transform'>;
}
declare module 'google-map-react/lib/utils/lib_geo/wrap.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/lib_geo/wrap'>;
}
declare module 'google-map-react/lib/utils/loaders/google_map_loader.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/loaders/google_map_loader'>;
}
declare module 'google-map-react/lib/utils/math/log2.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/math/log2'>;
}
declare module 'google-map-react/lib/utils/pick.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/pick'>;
}
declare module 'google-map-react/lib/utils/raf.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/raf'>;
}
declare module 'google-map-react/lib/utils/utils.js' {
  declare module.exports: $Exports<'google-map-react/lib/utils/utils'>;
}
declare module 'google-map-react/test/components/GoogleMap.spec.js' {
  declare module.exports: $Exports<'google-map-react/test/components/GoogleMap.spec'>;
}
declare module 'google-map-react/test/components/utils/jsdomInit.js' {
  declare module.exports: $Exports<'google-map-react/test/components/utils/jsdomInit'>;
}
declare module 'google-map-react/utils/index.js' {
  declare module.exports: $Exports<'google-map-react/utils/index'>;
}
declare module 'google-map-react/webpack.config.base.js' {
  declare module.exports: $Exports<'google-map-react/webpack.config.base'>;
}
declare module 'google-map-react/webpack.config.dev.js' {
  declare module.exports: $Exports<'google-map-react/webpack.config.dev'>;
}
declare module 'google-map-react/webpack.config.prod.js' {
  declare module.exports: $Exports<'google-map-react/webpack.config.prod'>;
}
