// flow-typed signature: 6313ab7390fd3870553e142164793b8a
// flow-typed version: <<STUB>>/highlight-loader_v^0.7.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'highlight-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'highlight-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'highlight-loader/demo/demo_index' {
  declare module.exports: any;
}

declare module 'highlight-loader/demo/run_demo' {
  declare module.exports: any;
}

declare module 'highlight-loader/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'highlight-loader/demo/demo_index.js' {
  declare module.exports: $Exports<'highlight-loader/demo/demo_index'>;
}
declare module 'highlight-loader/demo/run_demo.js' {
  declare module.exports: $Exports<'highlight-loader/demo/run_demo'>;
}
declare module 'highlight-loader/index' {
  declare module.exports: $Exports<'highlight-loader'>;
}
declare module 'highlight-loader/index.js' {
  declare module.exports: $Exports<'highlight-loader'>;
}
declare module 'highlight-loader/test.js' {
  declare module.exports: $Exports<'highlight-loader/test'>;
}
