// flow-typed signature: 4872481c74e9c324e43d832ccd268fb3
// flow-typed version: <<STUB>>/lapanoid-prettier_v^0.14.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lapanoid-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lapanoid-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lapanoid-prettier/bin/prettier' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/docs/prettier.min' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/docs/rollup.config' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/src/comments' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/src/deprecated' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/src/doc-builders' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/src/doc-debug' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/src/doc-printer' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/src/doc-utils' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/src/fast-path' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/src/options' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/src/parser' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/src/printer' {
  declare module.exports: any;
}

declare module 'lapanoid-prettier/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lapanoid-prettier/bin/prettier.js' {
  declare module.exports: $Exports<'lapanoid-prettier/bin/prettier'>;
}
declare module 'lapanoid-prettier/docs/prettier.min.js' {
  declare module.exports: $Exports<'lapanoid-prettier/docs/prettier.min'>;
}
declare module 'lapanoid-prettier/docs/rollup.config.js' {
  declare module.exports: $Exports<'lapanoid-prettier/docs/rollup.config'>;
}
declare module 'lapanoid-prettier/index' {
  declare module.exports: $Exports<'lapanoid-prettier'>;
}
declare module 'lapanoid-prettier/index.js' {
  declare module.exports: $Exports<'lapanoid-prettier'>;
}
declare module 'lapanoid-prettier/src/comments.js' {
  declare module.exports: $Exports<'lapanoid-prettier/src/comments'>;
}
declare module 'lapanoid-prettier/src/deprecated.js' {
  declare module.exports: $Exports<'lapanoid-prettier/src/deprecated'>;
}
declare module 'lapanoid-prettier/src/doc-builders.js' {
  declare module.exports: $Exports<'lapanoid-prettier/src/doc-builders'>;
}
declare module 'lapanoid-prettier/src/doc-debug.js' {
  declare module.exports: $Exports<'lapanoid-prettier/src/doc-debug'>;
}
declare module 'lapanoid-prettier/src/doc-printer.js' {
  declare module.exports: $Exports<'lapanoid-prettier/src/doc-printer'>;
}
declare module 'lapanoid-prettier/src/doc-utils.js' {
  declare module.exports: $Exports<'lapanoid-prettier/src/doc-utils'>;
}
declare module 'lapanoid-prettier/src/fast-path.js' {
  declare module.exports: $Exports<'lapanoid-prettier/src/fast-path'>;
}
declare module 'lapanoid-prettier/src/options.js' {
  declare module.exports: $Exports<'lapanoid-prettier/src/options'>;
}
declare module 'lapanoid-prettier/src/parser.js' {
  declare module.exports: $Exports<'lapanoid-prettier/src/parser'>;
}
declare module 'lapanoid-prettier/src/printer.js' {
  declare module.exports: $Exports<'lapanoid-prettier/src/printer'>;
}
declare module 'lapanoid-prettier/src/util.js' {
  declare module.exports: $Exports<'lapanoid-prettier/src/util'>;
}
