// flow-typed signature: 77dc4e23b7aa6688e38408bf41ab88ce
// flow-typed version: <<STUB>>/monkey-hot-loader_v^0.0.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'monkey-hot-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'monkey-hot-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'monkey-hot-loader/makeIdentitySourceMap' {
  declare module.exports: any;
}

declare module 'monkey-hot-loader/patcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'monkey-hot-loader/index' {
  declare module.exports: $Exports<'monkey-hot-loader'>;
}
declare module 'monkey-hot-loader/index.js' {
  declare module.exports: $Exports<'monkey-hot-loader'>;
}
declare module 'monkey-hot-loader/makeIdentitySourceMap.js' {
  declare module.exports: $Exports<'monkey-hot-loader/makeIdentitySourceMap'>;
}
declare module 'monkey-hot-loader/patcher.js' {
  declare module.exports: $Exports<'monkey-hot-loader/patcher'>;
}
