// flow-typed signature: 900cb230e43a569ebf74aa505a3f48a6
// flow-typed version: <<STUB>>/noop-loader_v^1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'noop-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'noop-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'noop-loader/README' {
  declare module.exports: any;
}

// Filename aliases
declare module 'noop-loader/index' {
  declare module.exports: $Exports<'noop-loader'>;
}
declare module 'noop-loader/index.js' {
  declare module.exports: $Exports<'noop-loader'>;
}
declare module 'noop-loader/README.js' {
  declare module.exports: $Exports<'noop-loader/README'>;
}
