// flow-typed signature: c45456d8d118773ca3aca3e3ccca9cb7
// flow-typed version: <<STUB>>/parse_v1.6.14/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse/dist/parse-latest' {
  declare module.exports: any;
}

declare module 'parse/dist/parse-latest.min' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/Analytics' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/arrayContainsObject' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/canBeSerialized' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/Cloud' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/CoreManager' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/decode' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/encode' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/equals' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/escape' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/FacebookUtils' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/InstallationController' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/isRevocableSession' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ObjectState' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/Parse' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseACL' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseConfig' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/parseDate' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseError' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseFile' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseGeoPoint' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseInstallation' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseObject' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseOp' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParsePromise' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseQuery' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseRelation' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseRole' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseSession' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/ParseUser' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/Push' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/RESTController' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/Storage' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/StorageController.browser' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/StorageController.default' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/StorageController.react-native' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/TaskQueue' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/unique' {
  declare module.exports: any;
}

declare module 'parse/lib/browser/unsavedChildren' {
  declare module.exports: any;
}

declare module 'parse/lib/node/Analytics' {
  declare module.exports: any;
}

declare module 'parse/lib/node/arrayContainsObject' {
  declare module.exports: any;
}

declare module 'parse/lib/node/canBeSerialized' {
  declare module.exports: any;
}

declare module 'parse/lib/node/Cloud' {
  declare module.exports: any;
}

declare module 'parse/lib/node/CoreManager' {
  declare module.exports: any;
}

declare module 'parse/lib/node/decode' {
  declare module.exports: any;
}

declare module 'parse/lib/node/encode' {
  declare module.exports: any;
}

declare module 'parse/lib/node/equals' {
  declare module.exports: any;
}

declare module 'parse/lib/node/escape' {
  declare module.exports: any;
}

declare module 'parse/lib/node/FacebookUtils' {
  declare module.exports: any;
}

declare module 'parse/lib/node/InstallationController' {
  declare module.exports: any;
}

declare module 'parse/lib/node/isRevocableSession' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ObjectState' {
  declare module.exports: any;
}

declare module 'parse/lib/node/Parse' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseACL' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseConfig' {
  declare module.exports: any;
}

declare module 'parse/lib/node/parseDate' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseError' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseFile' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseGeoPoint' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseInstallation' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseObject' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseOp' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParsePromise' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseQuery' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseRelation' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseRole' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseSession' {
  declare module.exports: any;
}

declare module 'parse/lib/node/ParseUser' {
  declare module.exports: any;
}

declare module 'parse/lib/node/Push' {
  declare module.exports: any;
}

declare module 'parse/lib/node/RESTController' {
  declare module.exports: any;
}

declare module 'parse/lib/node/Storage' {
  declare module.exports: any;
}

declare module 'parse/lib/node/StorageController.browser' {
  declare module.exports: any;
}

declare module 'parse/lib/node/StorageController.default' {
  declare module.exports: any;
}

declare module 'parse/lib/node/StorageController.react-native' {
  declare module.exports: any;
}

declare module 'parse/lib/node/TaskQueue' {
  declare module.exports: any;
}

declare module 'parse/lib/node/unique' {
  declare module.exports: any;
}

declare module 'parse/lib/node/unsavedChildren' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/Analytics' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/arrayContainsObject' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/canBeSerialized' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/Cloud' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/CoreManager' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/decode' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/encode' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/equals' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/escape' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/FacebookUtils' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/InstallationController' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/isRevocableSession' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ObjectState' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/Parse' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseACL' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseConfig' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/parseDate' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseError' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseFile' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseGeoPoint' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseInstallation' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseObject' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseOp' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParsePromise' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseQuery' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseRelation' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseRole' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseSession' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseUser' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/Push' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/RESTController' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/Storage' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/StorageController.browser' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/StorageController.default' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/StorageController.react-native' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/TaskQueue' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/unique' {
  declare module.exports: any;
}

declare module 'parse/lib/react-native/unsavedChildren' {
  declare module.exports: any;
}

declare module 'parse/node' {
  declare module.exports: any;
}

declare module 'parse/react-native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parse/dist/parse-latest.js' {
  declare module.exports: $Exports<'parse/dist/parse-latest'>;
}
declare module 'parse/dist/parse-latest.min.js' {
  declare module.exports: $Exports<'parse/dist/parse-latest.min'>;
}
declare module 'parse/index' {
  declare module.exports: $Exports<'parse'>;
}
declare module 'parse/index.js' {
  declare module.exports: $Exports<'parse'>;
}
declare module 'parse/lib/browser/Analytics.js' {
  declare module.exports: $Exports<'parse/lib/browser/Analytics'>;
}
declare module 'parse/lib/browser/arrayContainsObject.js' {
  declare module.exports: $Exports<'parse/lib/browser/arrayContainsObject'>;
}
declare module 'parse/lib/browser/canBeSerialized.js' {
  declare module.exports: $Exports<'parse/lib/browser/canBeSerialized'>;
}
declare module 'parse/lib/browser/Cloud.js' {
  declare module.exports: $Exports<'parse/lib/browser/Cloud'>;
}
declare module 'parse/lib/browser/CoreManager.js' {
  declare module.exports: $Exports<'parse/lib/browser/CoreManager'>;
}
declare module 'parse/lib/browser/decode.js' {
  declare module.exports: $Exports<'parse/lib/browser/decode'>;
}
declare module 'parse/lib/browser/encode.js' {
  declare module.exports: $Exports<'parse/lib/browser/encode'>;
}
declare module 'parse/lib/browser/equals.js' {
  declare module.exports: $Exports<'parse/lib/browser/equals'>;
}
declare module 'parse/lib/browser/escape.js' {
  declare module.exports: $Exports<'parse/lib/browser/escape'>;
}
declare module 'parse/lib/browser/FacebookUtils.js' {
  declare module.exports: $Exports<'parse/lib/browser/FacebookUtils'>;
}
declare module 'parse/lib/browser/InstallationController.js' {
  declare module.exports: $Exports<'parse/lib/browser/InstallationController'>;
}
declare module 'parse/lib/browser/isRevocableSession.js' {
  declare module.exports: $Exports<'parse/lib/browser/isRevocableSession'>;
}
declare module 'parse/lib/browser/ObjectState.js' {
  declare module.exports: $Exports<'parse/lib/browser/ObjectState'>;
}
declare module 'parse/lib/browser/Parse.js' {
  declare module.exports: $Exports<'parse/lib/browser/Parse'>;
}
declare module 'parse/lib/browser/ParseACL.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseACL'>;
}
declare module 'parse/lib/browser/ParseConfig.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseConfig'>;
}
declare module 'parse/lib/browser/parseDate.js' {
  declare module.exports: $Exports<'parse/lib/browser/parseDate'>;
}
declare module 'parse/lib/browser/ParseError.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseError'>;
}
declare module 'parse/lib/browser/ParseFile.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseFile'>;
}
declare module 'parse/lib/browser/ParseGeoPoint.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseGeoPoint'>;
}
declare module 'parse/lib/browser/ParseInstallation.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseInstallation'>;
}
declare module 'parse/lib/browser/ParseObject.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseObject'>;
}
declare module 'parse/lib/browser/ParseOp.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseOp'>;
}
declare module 'parse/lib/browser/ParsePromise.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParsePromise'>;
}
declare module 'parse/lib/browser/ParseQuery.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseQuery'>;
}
declare module 'parse/lib/browser/ParseRelation.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseRelation'>;
}
declare module 'parse/lib/browser/ParseRole.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseRole'>;
}
declare module 'parse/lib/browser/ParseSession.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseSession'>;
}
declare module 'parse/lib/browser/ParseUser.js' {
  declare module.exports: $Exports<'parse/lib/browser/ParseUser'>;
}
declare module 'parse/lib/browser/Push.js' {
  declare module.exports: $Exports<'parse/lib/browser/Push'>;
}
declare module 'parse/lib/browser/RESTController.js' {
  declare module.exports: $Exports<'parse/lib/browser/RESTController'>;
}
declare module 'parse/lib/browser/Storage.js' {
  declare module.exports: $Exports<'parse/lib/browser/Storage'>;
}
declare module 'parse/lib/browser/StorageController.browser.js' {
  declare module.exports: $Exports<'parse/lib/browser/StorageController.browser'>;
}
declare module 'parse/lib/browser/StorageController.default.js' {
  declare module.exports: $Exports<'parse/lib/browser/StorageController.default'>;
}
declare module 'parse/lib/browser/StorageController.react-native.js' {
  declare module.exports: $Exports<'parse/lib/browser/StorageController.react-native'>;
}
declare module 'parse/lib/browser/TaskQueue.js' {
  declare module.exports: $Exports<'parse/lib/browser/TaskQueue'>;
}
declare module 'parse/lib/browser/unique.js' {
  declare module.exports: $Exports<'parse/lib/browser/unique'>;
}
declare module 'parse/lib/browser/unsavedChildren.js' {
  declare module.exports: $Exports<'parse/lib/browser/unsavedChildren'>;
}
declare module 'parse/lib/node/Analytics.js' {
  declare module.exports: $Exports<'parse/lib/node/Analytics'>;
}
declare module 'parse/lib/node/arrayContainsObject.js' {
  declare module.exports: $Exports<'parse/lib/node/arrayContainsObject'>;
}
declare module 'parse/lib/node/canBeSerialized.js' {
  declare module.exports: $Exports<'parse/lib/node/canBeSerialized'>;
}
declare module 'parse/lib/node/Cloud.js' {
  declare module.exports: $Exports<'parse/lib/node/Cloud'>;
}
declare module 'parse/lib/node/CoreManager.js' {
  declare module.exports: $Exports<'parse/lib/node/CoreManager'>;
}
declare module 'parse/lib/node/decode.js' {
  declare module.exports: $Exports<'parse/lib/node/decode'>;
}
declare module 'parse/lib/node/encode.js' {
  declare module.exports: $Exports<'parse/lib/node/encode'>;
}
declare module 'parse/lib/node/equals.js' {
  declare module.exports: $Exports<'parse/lib/node/equals'>;
}
declare module 'parse/lib/node/escape.js' {
  declare module.exports: $Exports<'parse/lib/node/escape'>;
}
declare module 'parse/lib/node/FacebookUtils.js' {
  declare module.exports: $Exports<'parse/lib/node/FacebookUtils'>;
}
declare module 'parse/lib/node/InstallationController.js' {
  declare module.exports: $Exports<'parse/lib/node/InstallationController'>;
}
declare module 'parse/lib/node/isRevocableSession.js' {
  declare module.exports: $Exports<'parse/lib/node/isRevocableSession'>;
}
declare module 'parse/lib/node/ObjectState.js' {
  declare module.exports: $Exports<'parse/lib/node/ObjectState'>;
}
declare module 'parse/lib/node/Parse.js' {
  declare module.exports: $Exports<'parse/lib/node/Parse'>;
}
declare module 'parse/lib/node/ParseACL.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseACL'>;
}
declare module 'parse/lib/node/ParseConfig.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseConfig'>;
}
declare module 'parse/lib/node/parseDate.js' {
  declare module.exports: $Exports<'parse/lib/node/parseDate'>;
}
declare module 'parse/lib/node/ParseError.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseError'>;
}
declare module 'parse/lib/node/ParseFile.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseFile'>;
}
declare module 'parse/lib/node/ParseGeoPoint.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseGeoPoint'>;
}
declare module 'parse/lib/node/ParseInstallation.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseInstallation'>;
}
declare module 'parse/lib/node/ParseObject.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseObject'>;
}
declare module 'parse/lib/node/ParseOp.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseOp'>;
}
declare module 'parse/lib/node/ParsePromise.js' {
  declare module.exports: $Exports<'parse/lib/node/ParsePromise'>;
}
declare module 'parse/lib/node/ParseQuery.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseQuery'>;
}
declare module 'parse/lib/node/ParseRelation.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseRelation'>;
}
declare module 'parse/lib/node/ParseRole.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseRole'>;
}
declare module 'parse/lib/node/ParseSession.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseSession'>;
}
declare module 'parse/lib/node/ParseUser.js' {
  declare module.exports: $Exports<'parse/lib/node/ParseUser'>;
}
declare module 'parse/lib/node/Push.js' {
  declare module.exports: $Exports<'parse/lib/node/Push'>;
}
declare module 'parse/lib/node/RESTController.js' {
  declare module.exports: $Exports<'parse/lib/node/RESTController'>;
}
declare module 'parse/lib/node/Storage.js' {
  declare module.exports: $Exports<'parse/lib/node/Storage'>;
}
declare module 'parse/lib/node/StorageController.browser.js' {
  declare module.exports: $Exports<'parse/lib/node/StorageController.browser'>;
}
declare module 'parse/lib/node/StorageController.default.js' {
  declare module.exports: $Exports<'parse/lib/node/StorageController.default'>;
}
declare module 'parse/lib/node/StorageController.react-native.js' {
  declare module.exports: $Exports<'parse/lib/node/StorageController.react-native'>;
}
declare module 'parse/lib/node/TaskQueue.js' {
  declare module.exports: $Exports<'parse/lib/node/TaskQueue'>;
}
declare module 'parse/lib/node/unique.js' {
  declare module.exports: $Exports<'parse/lib/node/unique'>;
}
declare module 'parse/lib/node/unsavedChildren.js' {
  declare module.exports: $Exports<'parse/lib/node/unsavedChildren'>;
}
declare module 'parse/lib/react-native/Analytics.js' {
  declare module.exports: $Exports<'parse/lib/react-native/Analytics'>;
}
declare module 'parse/lib/react-native/arrayContainsObject.js' {
  declare module.exports: $Exports<'parse/lib/react-native/arrayContainsObject'>;
}
declare module 'parse/lib/react-native/canBeSerialized.js' {
  declare module.exports: $Exports<'parse/lib/react-native/canBeSerialized'>;
}
declare module 'parse/lib/react-native/Cloud.js' {
  declare module.exports: $Exports<'parse/lib/react-native/Cloud'>;
}
declare module 'parse/lib/react-native/CoreManager.js' {
  declare module.exports: $Exports<'parse/lib/react-native/CoreManager'>;
}
declare module 'parse/lib/react-native/decode.js' {
  declare module.exports: $Exports<'parse/lib/react-native/decode'>;
}
declare module 'parse/lib/react-native/encode.js' {
  declare module.exports: $Exports<'parse/lib/react-native/encode'>;
}
declare module 'parse/lib/react-native/equals.js' {
  declare module.exports: $Exports<'parse/lib/react-native/equals'>;
}
declare module 'parse/lib/react-native/escape.js' {
  declare module.exports: $Exports<'parse/lib/react-native/escape'>;
}
declare module 'parse/lib/react-native/FacebookUtils.js' {
  declare module.exports: $Exports<'parse/lib/react-native/FacebookUtils'>;
}
declare module 'parse/lib/react-native/InstallationController.js' {
  declare module.exports: $Exports<'parse/lib/react-native/InstallationController'>;
}
declare module 'parse/lib/react-native/isRevocableSession.js' {
  declare module.exports: $Exports<'parse/lib/react-native/isRevocableSession'>;
}
declare module 'parse/lib/react-native/ObjectState.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ObjectState'>;
}
declare module 'parse/lib/react-native/Parse.js' {
  declare module.exports: $Exports<'parse/lib/react-native/Parse'>;
}
declare module 'parse/lib/react-native/ParseACL.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseACL'>;
}
declare module 'parse/lib/react-native/ParseConfig.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseConfig'>;
}
declare module 'parse/lib/react-native/parseDate.js' {
  declare module.exports: $Exports<'parse/lib/react-native/parseDate'>;
}
declare module 'parse/lib/react-native/ParseError.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseError'>;
}
declare module 'parse/lib/react-native/ParseFile.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseFile'>;
}
declare module 'parse/lib/react-native/ParseGeoPoint.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseGeoPoint'>;
}
declare module 'parse/lib/react-native/ParseInstallation.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseInstallation'>;
}
declare module 'parse/lib/react-native/ParseObject.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseObject'>;
}
declare module 'parse/lib/react-native/ParseOp.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseOp'>;
}
declare module 'parse/lib/react-native/ParsePromise.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParsePromise'>;
}
declare module 'parse/lib/react-native/ParseQuery.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseQuery'>;
}
declare module 'parse/lib/react-native/ParseRelation.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseRelation'>;
}
declare module 'parse/lib/react-native/ParseRole.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseRole'>;
}
declare module 'parse/lib/react-native/ParseSession.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseSession'>;
}
declare module 'parse/lib/react-native/ParseUser.js' {
  declare module.exports: $Exports<'parse/lib/react-native/ParseUser'>;
}
declare module 'parse/lib/react-native/Push.js' {
  declare module.exports: $Exports<'parse/lib/react-native/Push'>;
}
declare module 'parse/lib/react-native/RESTController.js' {
  declare module.exports: $Exports<'parse/lib/react-native/RESTController'>;
}
declare module 'parse/lib/react-native/Storage.js' {
  declare module.exports: $Exports<'parse/lib/react-native/Storage'>;
}
declare module 'parse/lib/react-native/StorageController.browser.js' {
  declare module.exports: $Exports<'parse/lib/react-native/StorageController.browser'>;
}
declare module 'parse/lib/react-native/StorageController.default.js' {
  declare module.exports: $Exports<'parse/lib/react-native/StorageController.default'>;
}
declare module 'parse/lib/react-native/StorageController.react-native.js' {
  declare module.exports: $Exports<'parse/lib/react-native/StorageController.react-native'>;
}
declare module 'parse/lib/react-native/TaskQueue.js' {
  declare module.exports: $Exports<'parse/lib/react-native/TaskQueue'>;
}
declare module 'parse/lib/react-native/unique.js' {
  declare module.exports: $Exports<'parse/lib/react-native/unique'>;
}
declare module 'parse/lib/react-native/unsavedChildren.js' {
  declare module.exports: $Exports<'parse/lib/react-native/unsavedChildren'>;
}
declare module 'parse/node.js' {
  declare module.exports: $Exports<'parse/node'>;
}
declare module 'parse/react-native.js' {
  declare module.exports: $Exports<'parse/react-native'>;
}
