// flow-typed signature: 23c52bcb47c70402629b2737d2461e29
// flow-typed version: <<STUB>>/rc-collapse_v^1.6.10/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-collapse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-collapse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-collapse/es/Collapse' {
  declare module.exports: any;
}

declare module 'rc-collapse/es/index' {
  declare module.exports: any;
}

declare module 'rc-collapse/es/openAnimationFactory' {
  declare module.exports: any;
}

declare module 'rc-collapse/es/Panel' {
  declare module.exports: any;
}

declare module 'rc-collapse/es/PanelContent' {
  declare module.exports: any;
}

declare module 'rc-collapse/lib/Collapse' {
  declare module.exports: any;
}

declare module 'rc-collapse/lib/index' {
  declare module.exports: any;
}

declare module 'rc-collapse/lib/openAnimationFactory' {
  declare module.exports: any;
}

declare module 'rc-collapse/lib/Panel' {
  declare module.exports: any;
}

declare module 'rc-collapse/lib/PanelContent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-collapse/es/Collapse.js' {
  declare module.exports: $Exports<'rc-collapse/es/Collapse'>;
}
declare module 'rc-collapse/es/index.js' {
  declare module.exports: $Exports<'rc-collapse/es/index'>;
}
declare module 'rc-collapse/es/openAnimationFactory.js' {
  declare module.exports: $Exports<'rc-collapse/es/openAnimationFactory'>;
}
declare module 'rc-collapse/es/Panel.js' {
  declare module.exports: $Exports<'rc-collapse/es/Panel'>;
}
declare module 'rc-collapse/es/PanelContent.js' {
  declare module.exports: $Exports<'rc-collapse/es/PanelContent'>;
}
declare module 'rc-collapse/lib/Collapse.js' {
  declare module.exports: $Exports<'rc-collapse/lib/Collapse'>;
}
declare module 'rc-collapse/lib/index.js' {
  declare module.exports: $Exports<'rc-collapse/lib/index'>;
}
declare module 'rc-collapse/lib/openAnimationFactory.js' {
  declare module.exports: $Exports<'rc-collapse/lib/openAnimationFactory'>;
}
declare module 'rc-collapse/lib/Panel.js' {
  declare module.exports: $Exports<'rc-collapse/lib/Panel'>;
}
declare module 'rc-collapse/lib/PanelContent.js' {
  declare module.exports: $Exports<'rc-collapse/lib/PanelContent'>;
}
