// flow-typed signature: 511f8322b2c001c441824a0dbc9fb986
// flow-typed version: <<STUB>>/react-component-playground_v^0.4.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-component-playground'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-component-playground' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-component-playground/build/bundle' {
  declare module.exports: any;
}

declare module 'react-component-playground/fixtures/component-playground/default' {
  declare module.exports: any;
}

declare module 'react-component-playground/fixtures/component-playground/full-screen' {
  declare module.exports: any;
}

declare module 'react-component-playground/fixtures/component-playground/not-enough-searching-chars' {
  declare module.exports: any;
}

declare module 'react-component-playground/fixtures/component-playground/search-without-results' {
  declare module.exports: any;
}

declare module 'react-component-playground/fixtures/component-playground/selected-fixture-and-editor-focused' {
  declare module.exports: any;
}

declare module 'react-component-playground/fixtures/component-playground/selected-fixture-and-editor' {
  declare module.exports: any;
}

declare module 'react-component-playground/fixtures/component-playground/selected-fixture-with-search' {
  declare module.exports: any;
}

declare module 'react-component-playground/fixtures/component-playground/selected-fixture' {
  declare module.exports: any;
}

declare module 'react-component-playground/karma.conf' {
  declare module.exports: any;
}

declare module 'react-component-playground/src/components/component-playground' {
  declare module.exports: any;
}

declare module 'react-component-playground/src/lib/is-serializable' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/bind-polyfill' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/default/events/handlers' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/default/render/children' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/default/render/dom' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/default/render/urls' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/default/transitions/mount' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/full-screen/render/dom' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/not-enough-searching-chars/events/handlers' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/search-without-results/events/handlers' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/search-without-results/render/dom' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture-and-editor-focused/events/handlers' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture-and-editor/events/dom' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture-and-editor/events/handlers' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture-and-editor/render/dom' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture-and-editor/render/urls' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture-with-search/events/handlers' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture-with-search/render/dom' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture/events/dom' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture/events/handlers' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture/render/children' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture/render/dom' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture/render/urls' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture/transitions/mount' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture/transitions/props' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/components/component-playground/selected-fixture/transitions/state' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/lib/get-url-props' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/lib/render-component' {
  declare module.exports: any;
}

declare module 'react-component-playground/tests/setup/spy-load-child' {
  declare module.exports: any;
}

declare module 'react-component-playground/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-component-playground/build/bundle.js' {
  declare module.exports: $Exports<'react-component-playground/build/bundle'>;
}
declare module 'react-component-playground/fixtures/component-playground/default.js' {
  declare module.exports: $Exports<'react-component-playground/fixtures/component-playground/default'>;
}
declare module 'react-component-playground/fixtures/component-playground/full-screen.js' {
  declare module.exports: $Exports<'react-component-playground/fixtures/component-playground/full-screen'>;
}
declare module 'react-component-playground/fixtures/component-playground/not-enough-searching-chars.js' {
  declare module.exports: $Exports<'react-component-playground/fixtures/component-playground/not-enough-searching-chars'>;
}
declare module 'react-component-playground/fixtures/component-playground/search-without-results.js' {
  declare module.exports: $Exports<'react-component-playground/fixtures/component-playground/search-without-results'>;
}
declare module 'react-component-playground/fixtures/component-playground/selected-fixture-and-editor-focused.js' {
  declare module.exports: $Exports<'react-component-playground/fixtures/component-playground/selected-fixture-and-editor-focused'>;
}
declare module 'react-component-playground/fixtures/component-playground/selected-fixture-and-editor.js' {
  declare module.exports: $Exports<'react-component-playground/fixtures/component-playground/selected-fixture-and-editor'>;
}
declare module 'react-component-playground/fixtures/component-playground/selected-fixture-with-search.js' {
  declare module.exports: $Exports<'react-component-playground/fixtures/component-playground/selected-fixture-with-search'>;
}
declare module 'react-component-playground/fixtures/component-playground/selected-fixture.js' {
  declare module.exports: $Exports<'react-component-playground/fixtures/component-playground/selected-fixture'>;
}
declare module 'react-component-playground/karma.conf.js' {
  declare module.exports: $Exports<'react-component-playground/karma.conf'>;
}
declare module 'react-component-playground/src/components/component-playground.jsx' {
  declare module.exports: $Exports<'react-component-playground/src/components/component-playground'>;
}
declare module 'react-component-playground/src/lib/is-serializable.js' {
  declare module.exports: $Exports<'react-component-playground/src/lib/is-serializable'>;
}
declare module 'react-component-playground/tests/bind-polyfill.js' {
  declare module.exports: $Exports<'react-component-playground/tests/bind-polyfill'>;
}
declare module 'react-component-playground/tests/components/component-playground/default/events/handlers.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/default/events/handlers'>;
}
declare module 'react-component-playground/tests/components/component-playground/default/render/children.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/default/render/children'>;
}
declare module 'react-component-playground/tests/components/component-playground/default/render/dom.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/default/render/dom'>;
}
declare module 'react-component-playground/tests/components/component-playground/default/render/urls.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/default/render/urls'>;
}
declare module 'react-component-playground/tests/components/component-playground/default/transitions/mount.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/default/transitions/mount'>;
}
declare module 'react-component-playground/tests/components/component-playground/full-screen/render/dom.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/full-screen/render/dom'>;
}
declare module 'react-component-playground/tests/components/component-playground/not-enough-searching-chars/events/handlers.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/not-enough-searching-chars/events/handlers'>;
}
declare module 'react-component-playground/tests/components/component-playground/search-without-results/events/handlers.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/search-without-results/events/handlers'>;
}
declare module 'react-component-playground/tests/components/component-playground/search-without-results/render/dom.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/search-without-results/render/dom'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture-and-editor-focused/events/handlers.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture-and-editor-focused/events/handlers'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture-and-editor/events/dom.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture-and-editor/events/dom'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture-and-editor/events/handlers.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture-and-editor/events/handlers'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture-and-editor/render/dom.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture-and-editor/render/dom'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture-and-editor/render/urls.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture-and-editor/render/urls'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture-with-search/events/handlers.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture-with-search/events/handlers'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture-with-search/render/dom.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture-with-search/render/dom'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture/events/dom.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture/events/dom'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture/events/handlers.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture/events/handlers'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture/render/children.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture/render/children'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture/render/dom.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture/render/dom'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture/render/urls.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture/render/urls'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture/transitions/mount.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture/transitions/mount'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture/transitions/props.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture/transitions/props'>;
}
declare module 'react-component-playground/tests/components/component-playground/selected-fixture/transitions/state.js' {
  declare module.exports: $Exports<'react-component-playground/tests/components/component-playground/selected-fixture/transitions/state'>;
}
declare module 'react-component-playground/tests/lib/get-url-props.js' {
  declare module.exports: $Exports<'react-component-playground/tests/lib/get-url-props'>;
}
declare module 'react-component-playground/tests/lib/render-component.js' {
  declare module.exports: $Exports<'react-component-playground/tests/lib/render-component'>;
}
declare module 'react-component-playground/tests/setup/spy-load-child.js' {
  declare module.exports: $Exports<'react-component-playground/tests/setup/spy-load-child'>;
}
declare module 'react-component-playground/webpack.config.js' {
  declare module.exports: $Exports<'react-component-playground/webpack.config'>;
}
