// flow-typed signature: 31170687509f84ae363c74403ab4e1d1
// flow-typed version: <<STUB>>/react-telephone-input_v3.4.5/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-telephone-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-telephone-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-telephone-input/dist/react-telephone-input' {
  declare module.exports: any;
}

declare module 'react-telephone-input/dist/react-telephone-input.min' {
  declare module.exports: any;
}

declare module 'react-telephone-input/example/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-telephone-input/example/dist/common' {
  declare module.exports: any;
}

declare module 'react-telephone-input/example/dist/example' {
  declare module.exports: any;
}

declare module 'react-telephone-input/example/src/example' {
  declare module.exports: any;
}

declare module 'react-telephone-input/gulpfile' {
  declare module.exports: any;
}

declare module 'react-telephone-input/lib/country_data' {
  declare module.exports: any;
}

declare module 'react-telephone-input/lib/ReactTelephoneInput' {
  declare module.exports: any;
}

declare module 'react-telephone-input/lib/withStyles' {
  declare module.exports: any;
}

declare module 'react-telephone-input/src/country_data' {
  declare module.exports: any;
}

declare module 'react-telephone-input/src/ReactTelephoneInput' {
  declare module.exports: any;
}

declare module 'react-telephone-input/src/withStyles' {
  declare module.exports: any;
}

declare module 'react-telephone-input/test/ReactTelephoneInput-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-telephone-input/dist/react-telephone-input.js' {
  declare module.exports: $Exports<'react-telephone-input/dist/react-telephone-input'>;
}
declare module 'react-telephone-input/dist/react-telephone-input.min.js' {
  declare module.exports: $Exports<'react-telephone-input/dist/react-telephone-input.min'>;
}
declare module 'react-telephone-input/example/dist/bundle.js' {
  declare module.exports: $Exports<'react-telephone-input/example/dist/bundle'>;
}
declare module 'react-telephone-input/example/dist/common.js' {
  declare module.exports: $Exports<'react-telephone-input/example/dist/common'>;
}
declare module 'react-telephone-input/example/dist/example.js' {
  declare module.exports: $Exports<'react-telephone-input/example/dist/example'>;
}
declare module 'react-telephone-input/example/src/example.js' {
  declare module.exports: $Exports<'react-telephone-input/example/src/example'>;
}
declare module 'react-telephone-input/gulpfile.js' {
  declare module.exports: $Exports<'react-telephone-input/gulpfile'>;
}
declare module 'react-telephone-input/lib/country_data.js' {
  declare module.exports: $Exports<'react-telephone-input/lib/country_data'>;
}
declare module 'react-telephone-input/lib/ReactTelephoneInput.js' {
  declare module.exports: $Exports<'react-telephone-input/lib/ReactTelephoneInput'>;
}
declare module 'react-telephone-input/lib/withStyles.js' {
  declare module.exports: $Exports<'react-telephone-input/lib/withStyles'>;
}
declare module 'react-telephone-input/src/country_data.js' {
  declare module.exports: $Exports<'react-telephone-input/src/country_data'>;
}
declare module 'react-telephone-input/src/ReactTelephoneInput.js' {
  declare module.exports: $Exports<'react-telephone-input/src/ReactTelephoneInput'>;
}
declare module 'react-telephone-input/src/withStyles.js' {
  declare module.exports: $Exports<'react-telephone-input/src/withStyles'>;
}
declare module 'react-telephone-input/test/ReactTelephoneInput-test.js' {
  declare module.exports: $Exports<'react-telephone-input/test/ReactTelephoneInput-test'>;
}
