// flow-typed signature: ff8519c6c8ecec6a7d62dae16400184b
// flow-typed version: <<STUB>>/react-router-sitemap_v^1.0.7/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-sitemap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-sitemap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-sitemap/index.es5' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/index' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/params-applier/index' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/params-applier/params-replacer' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/params-applier/query-applier' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/params-applier/rule-applier' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/params-applier/rules-applier' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/params-applier/values-applier' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/paths-filter/index' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/paths-filter/params-preparer' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/paths-splitter/index' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/routes-parser/index' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/routes-parser/path-builder' {
  declare module.exports: any;
}

declare module 'react-router-sitemap/lib/sitemap-builder/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-sitemap/index.es5.js' {
  declare module.exports: $Exports<'react-router-sitemap/index.es5'>;
}
declare module 'react-router-sitemap/index' {
  declare module.exports: $Exports<'react-router-sitemap'>;
}
declare module 'react-router-sitemap/index.js' {
  declare module.exports: $Exports<'react-router-sitemap'>;
}
declare module 'react-router-sitemap/lib/index.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/index'>;
}
declare module 'react-router-sitemap/lib/params-applier/index.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/params-applier/index'>;
}
declare module 'react-router-sitemap/lib/params-applier/params-replacer.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/params-applier/params-replacer'>;
}
declare module 'react-router-sitemap/lib/params-applier/query-applier.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/params-applier/query-applier'>;
}
declare module 'react-router-sitemap/lib/params-applier/rule-applier.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/params-applier/rule-applier'>;
}
declare module 'react-router-sitemap/lib/params-applier/rules-applier.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/params-applier/rules-applier'>;
}
declare module 'react-router-sitemap/lib/params-applier/values-applier.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/params-applier/values-applier'>;
}
declare module 'react-router-sitemap/lib/paths-filter/index.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/paths-filter/index'>;
}
declare module 'react-router-sitemap/lib/paths-filter/params-preparer.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/paths-filter/params-preparer'>;
}
declare module 'react-router-sitemap/lib/paths-splitter/index.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/paths-splitter/index'>;
}
declare module 'react-router-sitemap/lib/routes-parser/index.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/routes-parser/index'>;
}
declare module 'react-router-sitemap/lib/routes-parser/path-builder.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/routes-parser/path-builder'>;
}
declare module 'react-router-sitemap/lib/sitemap-builder/index.js' {
  declare module.exports: $Exports<'react-router-sitemap/lib/sitemap-builder/index'>;
}
