// flow-typed signature: 885abe60c4984be252fef7527eb34502
// flow-typed version: <<STUB>>/react-responsive-decorator_v0.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive-decorator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive-decorator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive-decorator/example/assets/scripts/app' {
  declare module.exports: any;
}

declare module 'react-responsive-decorator/example/src/app' {
  declare module.exports: any;
}

declare module 'react-responsive-decorator/example/src/MyComponent' {
  declare module.exports: any;
}

declare module 'react-responsive-decorator/Gruntfile' {
  declare module.exports: any;
}

declare module 'react-responsive-decorator/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive-decorator/example/assets/scripts/app.js' {
  declare module.exports: $Exports<'react-responsive-decorator/example/assets/scripts/app'>;
}
declare module 'react-responsive-decorator/example/src/app.js' {
  declare module.exports: $Exports<'react-responsive-decorator/example/src/app'>;
}
declare module 'react-responsive-decorator/example/src/MyComponent.js' {
  declare module.exports: $Exports<'react-responsive-decorator/example/src/MyComponent'>;
}
declare module 'react-responsive-decorator/Gruntfile.js' {
  declare module.exports: $Exports<'react-responsive-decorator/Gruntfile'>;
}
declare module 'react-responsive-decorator/lib/index.js' {
  declare module.exports: $Exports<'react-responsive-decorator/lib/index'>;
}
