// flow-typed signature: 6ba3ddde11b0561b979124b7b774dcf0
// flow-typed version: <<STUB>>/react-onclickoutside_v5.1.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-onclickoutside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-onclickoutside' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-onclickoutside/test/browser/testit' {
  declare module.exports: any;
}

declare module 'react-onclickoutside/test/karma.conf' {
  declare module.exports: any;
}

declare module 'react-onclickoutside/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-onclickoutside/index' {
  declare module.exports: $Exports<'react-onclickoutside'>;
}
declare module 'react-onclickoutside/index.js' {
  declare module.exports: $Exports<'react-onclickoutside'>;
}
declare module 'react-onclickoutside/test/browser/testit.js' {
  declare module.exports: $Exports<'react-onclickoutside/test/browser/testit'>;
}
declare module 'react-onclickoutside/test/karma.conf.js' {
  declare module.exports: $Exports<'react-onclickoutside/test/karma.conf'>;
}
declare module 'react-onclickoutside/test/test.js' {
  declare module.exports: $Exports<'react-onclickoutside/test/test'>;
}
