// flow-typed signature: ba25d86f6ff44c135cdef2dcf36505a3
// flow-typed version: <<STUB>>/react-slick_v0.12.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-slick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-slick' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-slick/dist/react-slick' {
  declare module.exports: any;
}

declare module 'react-slick/dist/react-slick.min' {
  declare module.exports: any;
}

declare module 'react-slick/docs/demos' {
  declare module.exports: any;
}

declare module 'react-slick/docs/docs' {
  declare module.exports: any;
}

declare module 'react-slick/docs/index' {
  declare module.exports: any;
}

declare module 'react-slick/docs/routes' {
  declare module.exports: any;
}

declare module 'react-slick/lib/arrows' {
  declare module.exports: any;
}

declare module 'react-slick/lib/default-props' {
  declare module.exports: any;
}

declare module 'react-slick/lib/dots' {
  declare module.exports: any;
}

declare module 'react-slick/lib/index' {
  declare module.exports: any;
}

declare module 'react-slick/lib/initial-state' {
  declare module.exports: any;
}

declare module 'react-slick/lib/inner-slider' {
  declare module.exports: any;
}

declare module 'react-slick/lib/mixins/event-handlers' {
  declare module.exports: any;
}

declare module 'react-slick/lib/mixins/helpers' {
  declare module.exports: any;
}

declare module 'react-slick/lib/mixins/ReactDOM' {
  declare module.exports: any;
}

declare module 'react-slick/lib/mixins/trackHelper' {
  declare module.exports: any;
}

declare module 'react-slick/lib/slider' {
  declare module.exports: any;
}

declare module 'react-slick/lib/track' {
  declare module.exports: any;
}

declare module 'react-slick/src/arrows' {
  declare module.exports: any;
}

declare module 'react-slick/src/default-props' {
  declare module.exports: any;
}

declare module 'react-slick/src/dots' {
  declare module.exports: any;
}

declare module 'react-slick/src/index' {
  declare module.exports: any;
}

declare module 'react-slick/src/initial-state' {
  declare module.exports: any;
}

declare module 'react-slick/src/inner-slider' {
  declare module.exports: any;
}

declare module 'react-slick/src/mixins/event-handlers' {
  declare module.exports: any;
}

declare module 'react-slick/src/mixins/helpers' {
  declare module.exports: any;
}

declare module 'react-slick/src/mixins/ReactDOM' {
  declare module.exports: any;
}

declare module 'react-slick/src/mixins/trackHelper' {
  declare module.exports: any;
}

declare module 'react-slick/src/slider' {
  declare module.exports: any;
}

declare module 'react-slick/src/track' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-slick/dist/react-slick.js' {
  declare module.exports: $Exports<'react-slick/dist/react-slick'>;
}
declare module 'react-slick/dist/react-slick.min.js' {
  declare module.exports: $Exports<'react-slick/dist/react-slick.min'>;
}
declare module 'react-slick/docs/demos.jsx' {
  declare module.exports: $Exports<'react-slick/docs/demos'>;
}
declare module 'react-slick/docs/docs.jsx' {
  declare module.exports: $Exports<'react-slick/docs/docs'>;
}
declare module 'react-slick/docs/index.jsx' {
  declare module.exports: $Exports<'react-slick/docs/index'>;
}
declare module 'react-slick/docs/routes.jsx' {
  declare module.exports: $Exports<'react-slick/docs/routes'>;
}
declare module 'react-slick/lib/arrows.js' {
  declare module.exports: $Exports<'react-slick/lib/arrows'>;
}
declare module 'react-slick/lib/default-props.js' {
  declare module.exports: $Exports<'react-slick/lib/default-props'>;
}
declare module 'react-slick/lib/dots.js' {
  declare module.exports: $Exports<'react-slick/lib/dots'>;
}
declare module 'react-slick/lib/index.js' {
  declare module.exports: $Exports<'react-slick/lib/index'>;
}
declare module 'react-slick/lib/initial-state.js' {
  declare module.exports: $Exports<'react-slick/lib/initial-state'>;
}
declare module 'react-slick/lib/inner-slider.js' {
  declare module.exports: $Exports<'react-slick/lib/inner-slider'>;
}
declare module 'react-slick/lib/mixins/event-handlers.js' {
  declare module.exports: $Exports<'react-slick/lib/mixins/event-handlers'>;
}
declare module 'react-slick/lib/mixins/helpers.js' {
  declare module.exports: $Exports<'react-slick/lib/mixins/helpers'>;
}
declare module 'react-slick/lib/mixins/ReactDOM.js' {
  declare module.exports: $Exports<'react-slick/lib/mixins/ReactDOM'>;
}
declare module 'react-slick/lib/mixins/trackHelper.js' {
  declare module.exports: $Exports<'react-slick/lib/mixins/trackHelper'>;
}
declare module 'react-slick/lib/slider.js' {
  declare module.exports: $Exports<'react-slick/lib/slider'>;
}
declare module 'react-slick/lib/track.js' {
  declare module.exports: $Exports<'react-slick/lib/track'>;
}
declare module 'react-slick/src/arrows.jsx' {
  declare module.exports: $Exports<'react-slick/src/arrows'>;
}
declare module 'react-slick/src/default-props.js' {
  declare module.exports: $Exports<'react-slick/src/default-props'>;
}
declare module 'react-slick/src/dots.jsx' {
  declare module.exports: $Exports<'react-slick/src/dots'>;
}
declare module 'react-slick/src/index.js' {
  declare module.exports: $Exports<'react-slick/src/index'>;
}
declare module 'react-slick/src/initial-state.js' {
  declare module.exports: $Exports<'react-slick/src/initial-state'>;
}
declare module 'react-slick/src/inner-slider.jsx' {
  declare module.exports: $Exports<'react-slick/src/inner-slider'>;
}
declare module 'react-slick/src/mixins/event-handlers.js' {
  declare module.exports: $Exports<'react-slick/src/mixins/event-handlers'>;
}
declare module 'react-slick/src/mixins/helpers.js' {
  declare module.exports: $Exports<'react-slick/src/mixins/helpers'>;
}
declare module 'react-slick/src/mixins/ReactDOM.js' {
  declare module.exports: $Exports<'react-slick/src/mixins/ReactDOM'>;
}
declare module 'react-slick/src/mixins/trackHelper.js' {
  declare module.exports: $Exports<'react-slick/src/mixins/trackHelper'>;
}
declare module 'react-slick/src/slider.jsx' {
  declare module.exports: $Exports<'react-slick/src/slider'>;
}
declare module 'react-slick/src/track.jsx' {
  declare module.exports: $Exports<'react-slick/src/track'>;
}
