// flow-typed signature: 24fba37d0b83686a3ff05a0567b1c0ad
// flow-typed version: <<STUB>>/react-input-slider_v1.5.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-input-slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-input-slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-input-slider/dist/input-slider' {
  declare module.exports: any;
}

declare module 'react-input-slider/lib/input-slider' {
  declare module.exports: any;
}

declare module 'react-input-slider/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-input-slider/dist/input-slider.js' {
  declare module.exports: $Exports<'react-input-slider/dist/input-slider'>;
}
declare module 'react-input-slider/index' {
  declare module.exports: $Exports<'react-input-slider'>;
}
declare module 'react-input-slider/index.js' {
  declare module.exports: $Exports<'react-input-slider'>;
}
declare module 'react-input-slider/lib/input-slider.js' {
  declare module.exports: $Exports<'react-input-slider/lib/input-slider'>;
}
declare module 'react-input-slider/webpack.config.js' {
  declare module.exports: $Exports<'react-input-slider/webpack.config'>;
}
