// flow-typed signature: 4d726076d831bb91baf0f3fc6b973dd6
// flow-typed version: <<STUB>>/react-avatar-cropper_v0.1.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-avatar-cropper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-avatar-cropper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-avatar-cropper/dist/ReactAvatarCropper.min' {
  declare module.exports: any;
}

declare module 'react-avatar-cropper/example/bundle' {
  declare module.exports: any;
}

declare module 'react-avatar-cropper/example/smoothScroll.min' {
  declare module.exports: any;
}

declare module 'react-avatar-cropper/example/src/index' {
  declare module.exports: any;
}

declare module 'react-avatar-cropper/lib/__tests__/Cropper-test' {
  declare module.exports: any;
}

declare module 'react-avatar-cropper/lib/index' {
  declare module.exports: any;
}

declare module 'react-avatar-cropper/lib/utils' {
  declare module.exports: any;
}

declare module 'react-avatar-cropper/webpack.config.demo' {
  declare module.exports: any;
}

declare module 'react-avatar-cropper/webpack.config' {
  declare module.exports: any;
}

declare module 'react-avatar-cropper/webpack.config.production' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-avatar-cropper/dist/ReactAvatarCropper.min.js' {
  declare module.exports: $Exports<'react-avatar-cropper/dist/ReactAvatarCropper.min'>;
}
declare module 'react-avatar-cropper/example/bundle.js' {
  declare module.exports: $Exports<'react-avatar-cropper/example/bundle'>;
}
declare module 'react-avatar-cropper/example/smoothScroll.min.js' {
  declare module.exports: $Exports<'react-avatar-cropper/example/smoothScroll.min'>;
}
declare module 'react-avatar-cropper/example/src/index.js' {
  declare module.exports: $Exports<'react-avatar-cropper/example/src/index'>;
}
declare module 'react-avatar-cropper/lib/__tests__/Cropper-test.js' {
  declare module.exports: $Exports<'react-avatar-cropper/lib/__tests__/Cropper-test'>;
}
declare module 'react-avatar-cropper/lib/index.js' {
  declare module.exports: $Exports<'react-avatar-cropper/lib/index'>;
}
declare module 'react-avatar-cropper/lib/utils.js' {
  declare module.exports: $Exports<'react-avatar-cropper/lib/utils'>;
}
declare module 'react-avatar-cropper/webpack.config.demo.js' {
  declare module.exports: $Exports<'react-avatar-cropper/webpack.config.demo'>;
}
declare module 'react-avatar-cropper/webpack.config.js' {
  declare module.exports: $Exports<'react-avatar-cropper/webpack.config'>;
}
declare module 'react-avatar-cropper/webpack.config.production.js' {
  declare module.exports: $Exports<'react-avatar-cropper/webpack.config.production'>;
}
