// flow-typed signature: c5f748b187b1210e6d727f4533a1dc19
// flow-typed version: <<STUB>>/react-geosuggest_v1.20.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-geosuggest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-geosuggest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-geosuggest/dist/react-geosuggest' {
  declare module.exports: any;
}

declare module 'react-geosuggest/dist/react-geosuggest.min' {
  declare module.exports: any;
}

declare module 'react-geosuggest/module/defaults' {
  declare module.exports: any;
}

declare module 'react-geosuggest/module/filter-input-attributes' {
  declare module.exports: any;
}

declare module 'react-geosuggest/module/Geosuggest' {
  declare module.exports: any;
}

declare module 'react-geosuggest/module/input' {
  declare module.exports: any;
}

declare module 'react-geosuggest/module/prop-types' {
  declare module.exports: any;
}

declare module 'react-geosuggest/module/suggest-item' {
  declare module.exports: any;
}

declare module 'react-geosuggest/module/suggest-list' {
  declare module.exports: any;
}

declare module 'react-geosuggest/test/build.tests' {
  declare module.exports: any;
}

declare module 'react-geosuggest/test/fixtures/predictions' {
  declare module.exports: any;
}

declare module 'react-geosuggest/test/Geosuggest_spec' {
  declare module.exports: any;
}

declare module 'react-geosuggest/test/test_helper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-geosuggest/dist/react-geosuggest.js' {
  declare module.exports: $Exports<'react-geosuggest/dist/react-geosuggest'>;
}
declare module 'react-geosuggest/dist/react-geosuggest.min.js' {
  declare module.exports: $Exports<'react-geosuggest/dist/react-geosuggest.min'>;
}
declare module 'react-geosuggest/module/defaults.js' {
  declare module.exports: $Exports<'react-geosuggest/module/defaults'>;
}
declare module 'react-geosuggest/module/filter-input-attributes.js' {
  declare module.exports: $Exports<'react-geosuggest/module/filter-input-attributes'>;
}
declare module 'react-geosuggest/module/Geosuggest.js' {
  declare module.exports: $Exports<'react-geosuggest/module/Geosuggest'>;
}
declare module 'react-geosuggest/module/input.js' {
  declare module.exports: $Exports<'react-geosuggest/module/input'>;
}
declare module 'react-geosuggest/module/prop-types.js' {
  declare module.exports: $Exports<'react-geosuggest/module/prop-types'>;
}
declare module 'react-geosuggest/module/suggest-item.js' {
  declare module.exports: $Exports<'react-geosuggest/module/suggest-item'>;
}
declare module 'react-geosuggest/module/suggest-list.js' {
  declare module.exports: $Exports<'react-geosuggest/module/suggest-list'>;
}
declare module 'react-geosuggest/test/build.tests.js' {
  declare module.exports: $Exports<'react-geosuggest/test/build.tests'>;
}
declare module 'react-geosuggest/test/fixtures/predictions.js' {
  declare module.exports: $Exports<'react-geosuggest/test/fixtures/predictions'>;
}
declare module 'react-geosuggest/test/Geosuggest_spec.jsx' {
  declare module.exports: $Exports<'react-geosuggest/test/Geosuggest_spec'>;
}
declare module 'react-geosuggest/test/test_helper.js' {
  declare module.exports: $Exports<'react-geosuggest/test/test_helper'>;
}
