// flow-typed signature: 8eb1e643ecde25f7b0803792e3533425
// flow-typed version: <<STUB>>/react-redux-loading-bar_v1.1.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-redux-loading-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-redux-loading-bar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-redux-loading-bar/build/index' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/build/loading_bar_ducks' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/build/loading_bar_middleware' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/build/loading_bar_redux' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/build/loading_bar' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/spec/helpers/create_mock_store' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/spec/loading_bar_ducks' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/spec/loading_bar_middleware' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/spec/loading_bar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-redux-loading-bar/build/index.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/build/index'>;
}
declare module 'react-redux-loading-bar/build/loading_bar_ducks.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/build/loading_bar_ducks'>;
}
declare module 'react-redux-loading-bar/build/loading_bar_middleware.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/build/loading_bar_middleware'>;
}
declare module 'react-redux-loading-bar/build/loading_bar_redux.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/build/loading_bar_redux'>;
}
declare module 'react-redux-loading-bar/build/loading_bar.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/build/loading_bar'>;
}
declare module 'react-redux-loading-bar/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/coverage/lcov-report/prettify'>;
}
declare module 'react-redux-loading-bar/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/coverage/lcov-report/sorter'>;
}
declare module 'react-redux-loading-bar/spec/helpers/create_mock_store.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/spec/helpers/create_mock_store'>;
}
declare module 'react-redux-loading-bar/spec/loading_bar_ducks.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/spec/loading_bar_ducks'>;
}
declare module 'react-redux-loading-bar/spec/loading_bar_middleware.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/spec/loading_bar_middleware'>;
}
declare module 'react-redux-loading-bar/spec/loading_bar.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/spec/loading_bar'>;
}
