// flow-typed signature: 300968fdb36e307c7df434b3ea36ac8d
// flow-typed version: <<STUB>>/react-querystring-router_v^0.3.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-querystring-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-querystring-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-querystring-router/karma.conf' {
  declare module.exports: any;
}

declare module 'react-querystring-router/src/main' {
  declare module.exports: any;
}

declare module 'react-querystring-router/src/router' {
  declare module.exports: any;
}

declare module 'react-querystring-router/src/uri' {
  declare module.exports: any;
}

declare module 'react-querystring-router/tests/bind-polyfill' {
  declare module.exports: any;
}

declare module 'react-querystring-router/tests/router' {
  declare module.exports: any;
}

declare module 'react-querystring-router/tests/uri' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-querystring-router/karma.conf.js' {
  declare module.exports: $Exports<'react-querystring-router/karma.conf'>;
}
declare module 'react-querystring-router/src/main.js' {
  declare module.exports: $Exports<'react-querystring-router/src/main'>;
}
declare module 'react-querystring-router/src/router.js' {
  declare module.exports: $Exports<'react-querystring-router/src/router'>;
}
declare module 'react-querystring-router/src/uri.js' {
  declare module.exports: $Exports<'react-querystring-router/src/uri'>;
}
declare module 'react-querystring-router/tests/bind-polyfill.js' {
  declare module.exports: $Exports<'react-querystring-router/tests/bind-polyfill'>;
}
declare module 'react-querystring-router/tests/router.js' {
  declare module.exports: $Exports<'react-querystring-router/tests/router'>;
}
declare module 'react-querystring-router/tests/uri.js' {
  declare module.exports: $Exports<'react-querystring-router/tests/uri'>;
}
