// flow-typed signature: df5a062953a4fb121de6eea00c7fe10e
// flow-typed version: <<STUB>>/react-progress_v0.0.12/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-progress/dist/react-progress' {
  declare module.exports: any;
}

declare module 'react-progress/dist/react-progress.min' {
  declare module.exports: any;
}

declare module 'react-progress/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-progress/dist/react-progress.js' {
  declare module.exports: $Exports<'react-progress/dist/react-progress'>;
}
declare module 'react-progress/dist/react-progress.min.js' {
  declare module.exports: $Exports<'react-progress/dist/react-progress.min'>;
}
declare module 'react-progress/webpack.config.js' {
  declare module.exports: $Exports<'react-progress/webpack.config'>;
}
