// flow-typed signature: 7ef8f82f51b3fb9bfc38400ecf3f55cd
// flow-typed version: <<STUB>>/redux-cookie_v^0.5.9/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-cookie/lib/__tests__/redux-cookie-test' {
  declare module.exports: any;
}

declare module 'redux-cookie/lib/index' {
  declare module.exports: any;
}

declare module 'redux-cookie/src/__tests__/redux-cookie-test' {
  declare module.exports: any;
}

declare module 'redux-cookie/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-cookie/lib/__tests__/redux-cookie-test.js' {
  declare module.exports: $Exports<'redux-cookie/lib/__tests__/redux-cookie-test'>;
}
declare module 'redux-cookie/lib/index.js' {
  declare module.exports: $Exports<'redux-cookie/lib/index'>;
}
declare module 'redux-cookie/src/__tests__/redux-cookie-test.js' {
  declare module.exports: $Exports<'redux-cookie/src/__tests__/redux-cookie-test'>;
}
declare module 'redux-cookie/src/index.js' {
  declare module.exports: $Exports<'redux-cookie/src/index'>;
}
