// flow-typed signature: ffe0a8aa786ca44da668b2ef85b2fc74
// flow-typed version: <<STUB>>/vorpal_v1.11.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vorpal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vorpal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vorpal/dist/autocomplete' {
  declare module.exports: any;
}

declare module 'vorpal/dist/command-instance' {
  declare module.exports: any;
}

declare module 'vorpal/dist/command' {
  declare module.exports: any;
}

declare module 'vorpal/dist/history' {
  declare module.exports: any;
}

declare module 'vorpal/dist/intercept' {
  declare module.exports: any;
}

declare module 'vorpal/dist/local-storage' {
  declare module.exports: any;
}

declare module 'vorpal/dist/logger' {
  declare module.exports: any;
}

declare module 'vorpal/dist/option' {
  declare module.exports: any;
}

declare module 'vorpal/dist/session' {
  declare module.exports: any;
}

declare module 'vorpal/dist/ui' {
  declare module.exports: any;
}

declare module 'vorpal/dist/util' {
  declare module.exports: any;
}

declare module 'vorpal/dist/vorpal-commons' {
  declare module.exports: any;
}

declare module 'vorpal/dist/vorpal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vorpal/dist/autocomplete.js' {
  declare module.exports: $Exports<'vorpal/dist/autocomplete'>;
}
declare module 'vorpal/dist/command-instance.js' {
  declare module.exports: $Exports<'vorpal/dist/command-instance'>;
}
declare module 'vorpal/dist/command.js' {
  declare module.exports: $Exports<'vorpal/dist/command'>;
}
declare module 'vorpal/dist/history.js' {
  declare module.exports: $Exports<'vorpal/dist/history'>;
}
declare module 'vorpal/dist/intercept.js' {
  declare module.exports: $Exports<'vorpal/dist/intercept'>;
}
declare module 'vorpal/dist/local-storage.js' {
  declare module.exports: $Exports<'vorpal/dist/local-storage'>;
}
declare module 'vorpal/dist/logger.js' {
  declare module.exports: $Exports<'vorpal/dist/logger'>;
}
declare module 'vorpal/dist/option.js' {
  declare module.exports: $Exports<'vorpal/dist/option'>;
}
declare module 'vorpal/dist/session.js' {
  declare module.exports: $Exports<'vorpal/dist/session'>;
}
declare module 'vorpal/dist/ui.js' {
  declare module.exports: $Exports<'vorpal/dist/ui'>;
}
declare module 'vorpal/dist/util.js' {
  declare module.exports: $Exports<'vorpal/dist/util'>;
}
declare module 'vorpal/dist/vorpal-commons.js' {
  declare module.exports: $Exports<'vorpal/dist/vorpal-commons'>;
}
declare module 'vorpal/dist/vorpal.js' {
  declare module.exports: $Exports<'vorpal/dist/vorpal'>;
}
