// flow-typed signature: 007519591c43f0275c4f4d80d34d637a
// flow-typed version: <<STUB>>/webpack-notifier_v1.3.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-notifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-notifier/example/entry' {
  declare module.exports: any;
}

declare module 'webpack-notifier/example/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-notifier/example/entry.js' {
  declare module.exports: $Exports<'webpack-notifier/example/entry'>;
}
declare module 'webpack-notifier/example/webpack.config.js' {
  declare module.exports: $Exports<'webpack-notifier/example/webpack.config'>;
}
declare module 'webpack-notifier/index' {
  declare module.exports: $Exports<'webpack-notifier'>;
}
declare module 'webpack-notifier/index.js' {
  declare module.exports: $Exports<'webpack-notifier'>;
}
