// flow-typed signature: e047c3efe0645903d0fab46ec1c46468
// flow-typed version: <<STUB>>/yargs_v3.30.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yargs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yargs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yargs/lib/completion' {
  declare module.exports: any;
}

declare module 'yargs/lib/parser' {
  declare module.exports: any;
}

declare module 'yargs/lib/usage' {
  declare module.exports: any;
}

declare module 'yargs/lib/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yargs/index' {
  declare module.exports: $Exports<'yargs'>;
}
declare module 'yargs/index.js' {
  declare module.exports: $Exports<'yargs'>;
}
declare module 'yargs/lib/completion.js' {
  declare module.exports: $Exports<'yargs/lib/completion'>;
}
declare module 'yargs/lib/parser.js' {
  declare module.exports: $Exports<'yargs/lib/parser'>;
}
declare module 'yargs/lib/usage.js' {
  declare module.exports: $Exports<'yargs/lib/usage'>;
}
declare module 'yargs/lib/validation.js' {
  declare module.exports: $Exports<'yargs/lib/validation'>;
}
